name: 🧪 Real ScanVf Scraper Test

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  real_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests (real HTTP)
        run: npm run test:real

      - name: Send mail on failure
        if: failure()
        run: npx ts-node scripts/realTestMailer.ts
        env:
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
